name: macOS (aarch64)
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Clang 17
      run: brew install llvm@17
    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DRPP_TEST=ON
      env:
        CXX: /usr/local/opt/llvm/bin/clang++
    - name: Build
      run: cmake --build build -- -j
    - name: Test
      run: ctest --test-dir build --output-on-failure